name: tests

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Output personal information
        env:
          STUDENT_NAME: "Тарский Дмитрий Николаевич"
          GROUP_NUMBER: "М3115"
        run: |
          echo "ФИО: $STUDENT_NAME"
          echo "Группа: $GROUP_NUMBER"
          echo "GitHub username: ${{ github.actor }}"

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          fi

      - name: Run tests
        run: |
          python -m unittest discover tests/ "test_*.py" -v

      - name: Check code style
        run: |
          python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
